config/routes.rb
Rails.application.routes.draw do

  resources :lists do
    resources :tasks do
      delete "/remove", to: "tasks#image_remove"
    end
  end

  post "/change_status", to: "tasks#change_status"

 
  root to: 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  validates :title, presence:true 
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  validates :title, presence:true
  validate :start_date_cannot_be_in_the_past
  validate :due_date_cannot_be_in_the_past           
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://www.gianteagle.com/PageFiles/11386/thumbnail_Petcare_SmallAnimals_05012012.png"
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def default_values
    self.status ||= "Incomplete"
  end

  def mark_complete
    self.status = "Complete"
  end

  def complete?
    self.status = "Complete"
  end

  def self.future
    where("start_date > ?", Date.today)
  end
 
  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "cannot be in the past")
    end
  end
 
  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "cannot be in the past")
    end
  end

  def the_past?
    true if self.start_date.present? && self.start_date <= Date.today
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks
  end

  def index
    @lists = List.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash.now[:message] = "List has been created!"
      redirect_to root_path
    else
      flash.now[:errors] = @list.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    if @list.destroy
      flash.now[:message] = "List has been removed"
      redirect_to root_path
    else
      flash.now[:errors] = @list.errors.full_messages
      redirect_to root_path
    end
  end


  def list_params
  params.require(:list).permit(:title,
                               :description,
                              )
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.list_id = params[:list_id]
    if @task.save
      flash.now[:message] = "Task has been created!"
      redirect_to list_path(@task.list_id)
    else
      flash.now[:message] = @task.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
    @task.list_id = params[:list_id]
  end

  def update
    @task = Task.find(params[:id])
    @task.list_id = params[:list_id]
    if @task.update(task_params)
      flash.now[:message] = "Task Updated"
      redirect_to list_path(@task.list_id)
    else 
      flash.now[:message] = @task.full_messages.join(", ")
      render :edit
    end
  end

  def complete
    @task = Task.find(params[:format])
    @task.list_id = params[:list_id]
    @task.mark_complete
    @task.save!
    redirect_to list_path(@task.list_id)
  end

  def image_remove
    @task = Task.find(params[:task_id])
    @task.image = nil
    @task.save
    redirect_to list_path(@task.list_id)
  end

  def destroy
    @task = Task.find(params[:task_id])
    if @task.destroy
      flash.now[:message] = "List has been removed"
      redirect_to list_path(@task.list_id)
    else
      flash.now[:errors] = @list.errors.full_messages
      redirect_to root_path
    end
  end

  def change_status
    @task = Task.find(params[:task_id].to_i)
    @task.status = params[:status]
    if @task.save
      respond_with @task
    else
      respond_with({:errors => @task.errors}, :status => 422, :location => tasks_path)
    end
  end

private
  def task_params
    params.require(:task).permit(:title,
                                 :description,
                                 :start_date,
                                 :due_date,
                                 :image
                              )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => 'shared/nav' %>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <%= f.text_field :title, placeholder:"Title" %>
  <%= f.text_field :description, placeholder: "Description" %>
  <%= f.submit %>

<% flash.each do |type, message| %>
    <p> <%= message %> </p>
<%end%>

<% end %>

app/views/lists/_table_form.html.erb
<td class="title"><%="#{task.title}" %></td>
<td class="description"><%="#{task.description}" %></td>
<td class="start-date"><%= time_tag task.start_date %></td>
<td class="due-date"><%= time_tag task.due_date %></td>
<td class="task-status"><%="#{task.status}" %></td>
<td><%= image_tag task.image.url(:medium) %><%= link_to "Remove Image", list_task_remove_path(list_id: @list.id, task_id: task.id), method: :delete %> | </td>
<td><%= link_to "Edit Task", edit_list_task_path(@list.id, task) %> |    <%= link_to "Remove Task", list_task_path(list_id: @list.id, task_id: task.id), method: :delete %></td>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<h3> Let's change it up </h3>
<%= render partial: 'form' %>

app/views/lists/index.html.erb
<div class="index-container">

<h1> Your Lists </h1>

<%= button_to "Create New List", new_list_path, method: :get %>
  <% @lists.each do |list| %>
      <div class="col-lg-3">
      <tr>
        <td><strong><%= link_to "#{list.title} :", list_path(list) %></strong></td>
        <td><%= "#{list.description}" %></td>
        <td><%= link_to "Edit", edit_list_path(list) %></td>
        <td><%= link_to "Remove", list_path(list), method: :delete, data: { confirm: "Are you sure you want to remove this list?"} %></td>
      </tr>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<h3> What you want to call it? </h3>
<%= render partial: 'form' %>

app/views/lists/show.html.erb
<h1><%= "#{@list.title}" %></h1>
<h6><%= "#{@list.description}" %> </h6>

<p><input name="search-box" class="search-box" placeholder="Filter By Name"</p>

<p><%= button_to "Create New Task",
new_list_task_path(@list), method: :get %>  </p>

<ul><button class="show-future"><%="Show Future" %></button><button class="show-completed"><%="Show Complete" %></button></ul>

<table id="myTable" class="tablesorter"> 
  <thead>
    <tr>
      <th><strong>Title</strong></th>
      <th><strong>Description</strong></th>
      <th><strong>Start Date</strong></th>
      <th><strong>Due Date</strong></th>
      <th><strong>Status</strong></th>
      <th> Image </th>
    </tr>
  </thead>
  <tbody class="all-task">  
  <% @tasks.each do |task| %>
    <% if !task.the_past? %>
      <tr class="<%=task.status%> future" >
        <td class="title"><%="#{task.title}" %></td>
        <td class="description"><%="#{task.description}" %></td>
        <td class="start-date"><%= time_tag task.start_date %></td>
        <td class="due-date"><%= time_tag task.due_date %></td>
        <td><a href="#" class="task-status" data-id=<%=task.id %>><%= task.status %></a></td>
        <td><%= image_tag task.image.url(:thumb) %><%= link_to "Remove Image", list_task_remove_path(list_id: @list.id, task_id: task.id), method: :delete %> | </td>
        <td><%= link_to "Edit Task", edit_list_task_path(@list.id, task) %> |    <%= link_to "Remove Task", list_task_path(list_id: @list.id, task_id: task.id), method: :delete %></td>
      </tr>
      <% else %>
      <tr class="<%=task.status%>" >
        <td class="title"><%="#{task.title}" %></td>
        <td class="description"><%="#{task.description}" %></td>
        <td class="start-date"><%= time_tag task.start_date %></td>
        <td class="due-date"><%= time_tag task.due_date %></td>
        <td><a href="#" class="task-status" data-id=<%=task.id %>><%= task.status %></a></td>
        <td><%= image_tag task.image.url(:thumb) %><%= link_to "Remove Image", list_task_remove_path(list_id: @list.id, task_id: task.id), method: :delete %>  </td>
        <td><%= link_to "Edit Task", edit_list_task_path(@list.id, task) %> |    <%= link_to "Remove Task", list_task_path(list_id: @list.id, task_id: task.id), method: :delete %></td>
      </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/shared/_nav.html.erb
<%= nav_bar fixed: :top, brand: "Organize Yo Life", responsive: true do %>

<% end %>

app/views/tasks/_form.html.erb
<%= form_for @task, url: list_tasks_path(params[:list_id]), method: :post do |f| %>
  <%= f.text_field :title, placeholder:"Title" %>
  <%= f.text_field :description, placeholder:"Description" %>
  <%= f.date_field :start_date, plaecholder: "mm/dd/year" %>
  <%= f.date_field :due_date, plaecholder: "mm/dd/year" %>
  <%= f.file_field :image %>
  <%= f.submit %>


  <% flash.each do |type, message| %>
    <p> <%= message %></p>
  <%end %>
  
<% end %> 

app/views/tasks/edit.html.erb
<h3> Let's change it up </h3>
<%= form_for @task, url: list_task_path(params[:list_id], @task.id) do |f| %>
  <%= f.text_field :title, placeholder:"Title" %>
  <%= f.text_field :description, placeholder:"Description" %>
  <%= f.date_field :start_date, plaecholder: "mm/dd/year" %>
  <%= f.date_field :due_date, plaecholder: "mm/dd/year" %>
  <%= f.submit %>


  <% flash.each do |type, message| %>
    <p> <%= message %></p>
  <%end %>
<% end %>

app/views/tasks/new.html.erb
<h1> What's on the to add? </h1>

<%= render partial: 'form'  %>